### ISSUE TITLE
Compass Manager -  implement basic e2e tests for Compass Manager

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/compass-manager#14] opened 2023-05-18 09:26 UTC
We must consider creating component test for Compass Manager. Such a test could work in a similar way as Compass Runtime Agent test. It could register itself in DEV Compass.

**Comment by tobiscr** [comment] 2023-12-29 16:08
Closing this issue as duplicate of #65

**Closed by tobiscr** 2023-12-29 16:08 UTC
Labels: area/application-connector
